export const menuData = [
  {
    id: '1',
    name: 'Chicken Menu',
    items: [
      {
        id: '1',
        name: 'Spicy Chicken Breast 6PCS',
        description:
          'Our signature Chickenjoy hot spicy fried chicken Breast served with 1 side. This is a great skinless, chicken breast recipe that can be served over salad greens or as an entree!',
        price: "Rs 350",       
        image: require('../assets/images/chickenBreast.png'),
      },
      {
        id: '2',
        name: 'Chicken Chow Mein',
        description: 'This chow mein is just like what you get at your favorite Chinese restaurant! It is made with tender noodles, fresh sauteed veggies, lean chicken, and a simple savory sauce. A crave-worthy dinner!',
        price: "Rs 190",
        image: require('../assets/images/chowMein.jpg'),
      },
      {
        id: '3',
        name: 'Sweet & Sour Chicken',
        description:
          'Skip the take out - this Sweet and Sour Chicken Recipe is so good that you’ll put it on the permanent rotation. Chicken is coated in a sweet and sticky sauce and baked to perfection',
        price: "Rs 250",
        image: require('../assets/images/sweet&sour.jpg'),
      },
      {
        id: '4',
        name: 'Chicken with Garlic Sauce',
        description:
          'Pan-seared chicken thighs prepared with an incredible wine and garlic sauce',
        price: "Rs 275",
        image: require('../assets/images/GarlicSauceChicken.jpg'),
      },
      {
        id: '5',
        name: 'Peanut Butter Chicken',
        description:'A QUICK one-skillet easy weeknight dinner that’s huge on flavor, low on fat & loaded with tender, juicy chicken, lusciously creamy, wonderfully fragrant, comforting peanut sauce infused with garlic, ginger, basil & coconut milk',
        price: "Rs 300",
        image: require('../assets/images/peanutButterChicken.jpg'),
      },
    ],
  },
  {
    id: '2',
    name: 'Dessert',
    items: [
      {
        id: '1',
        name: 'Purple Velvet Cake',
        description: 'It tastes just like red velvet cake – it has a mild chocolate flavor with a soft, velvety texture.This purple velvet cake with blueberry & white chocolate cream cheese frosting (in purple) is adapted from an Epicurious red velvet cake.',
        price: "Rs 125",
        image: require('../assets/images/purplevelvetcake.png'),
      },
      {
        id: '2',
        name: 'Peach Mango Pie',
        description: 'Sweet, flaky & buttery Peach Mango Pie crust plus sweet and bright fruit filling, these peach mango pies are delicious pocket-sized desserts that you can eat anytime',
        price: "Rs 110",
        image: require('../assets/images/mangopie.jpg'),
      },
      {
        id: '3',
        name: 'Chocolate Ice Cream',
        description: 'Everyone needs a good recipe for ice cream. This is very rich, so generally one scoop should be enough (seriously!)',
        price: "Rs 75",
        image: require('../assets/images/chocoIceCream.jpg'),
      },
      {
        id: '4',
        name: 'Strawberry Cheesecake',
        description: 'This Strawberry Cheesecake is a showstopper!',
        price: "Rs 200",
        image: require('../assets/images/cheesecake.jpg'),
      },
      {
        id: '5',
        name: 'Flan au caramel',
        description: 'Creme caramel is a baked custard with a layer of clear caramel. Rich, creamy, with a velvety smooth texture; this is sheer luxury',
        price: "Rs 95",
        image: require('../assets/images/flan.jpg'),
      },
      {
        id: '6',
        name: 'Mango Dessert Cups',
        description: 'Mango Dessert Cups are insanely delicious and the creamiest dessert cups and they are served sweet & cold! Perfect weekend treat',
        price: "Rs 165",
        image: require('../assets/images/mangocups.jpg'),
      },
      {
        id: '7',
        name: 'Vermicelli Kheer Recipe',
        description: 'A popular South Indian dessert dish for any festival and special occasion',
        price: "Rs 135",
        image: require('../assets/images/vermicelliKheer.jpg'),
      },
      {
        id: '8',
        name: 'Strawberry Shortcake Icebox',
        description: 'Take fresh strawberries and cream to the next level with this Gluten Free Strawberry shortcake. Fluffy whipped cream, juicy strawberries and cream crackers are all you need to make this potluck favorite!',
        price: "Rs 175",
        image: require('../assets/images/shortcake.jpg'),
      },
    ],
  },
  {
    id: '3',
    name: 'Italian Dish',
    items: [
      {
        id: '0',
        name: 'Risotto',
        description: 'What to serve with risotto? Lemon arugula salad! It comes together in minutes, and it is the perfect fresh and tangy counterpoint to a meal',
        price: "Rs 260",
        image: require('../assets/images/risotto.jpg'),
      },
      {
        id: '1',
        name: 'Ravioli',
        description: 'Creamy Tuscan Ravioli. Store-bought ravioli tossed in a garlicky sun-dried tomato cream sauce topped with baby spinach, basil, and parmesan chees',
        price: "Rs 325",
        image: require('../assets/images/ravioli.jpg'),
      },
      {
        id: '2',
        name: 'Gnocchi',
        description: 'A delicious sage, butter, garlic and cheese sauce makes a delicious side dish or complete meal',
        price: "Rs 150",
        image: require('../assets/images/gnochhi.jpg'),
      },
      {
        id: '3',
        name: 'Lasagne al forno',
        description: 'Lasagne al forno is an Italian classic dish. Here is prepared with sirloin, but you can replace it with roasted vegetables, fish, rabbit. Yummy!!',
        price: "Rs 285",
        image: require('../assets/images/lasagne.jpg'),
      },
      {
        id: '4',
        name: 'Carbonara',
        description: 'This dish is a deli egg-bacon-and-cheese-on-a-roll that has been pasta-fied, fancified, fetishized and turned into an Italian tradition that, like many inviolate Italian traditions, is actually far less old than the Mayflower.',
        price: "Rs 320",
        image: require('../assets/images/carbonara.jpg'),
      },

    ],
  },
  {
    id: '4',
    name: 'Indian Cuisine',
    items: [
      {
        id: '0',
        name: 'Chicken Tikka Masala',
        description: 'Full of incredible flavours, it rivals any Indian restaurant! Aromatic golden chicken pieces in an incredible creamy curry sauce, this Chicken Tikka Masala recipe is one of the best you will try!',
        price: "Rs 285",
        image: require('../assets/images/tikka.jpg'),
      },
      {
        id: '1',
        name: 'Butter Chicken Masala',
        description: 'Served with basmati rice and warm naan bread!',
        price: "Rs 300",
        image: require('../assets/images/butterChicken.jpg'),
      },
      {
        id: '2',
        name: 'Veg Kheema',
        description: 'ry this delicious recipe for a keema curry cooked with Quorn Mince, peppers, onions, peas and coriander. Quorn Mince is high in protein and low in saturated fat for a healthy mid-week meal',
        price: "Rs 275",
        image: require('../assets/images/kheema.jpg'),
      },
      {        
        id: '3',
        name: 'Biryani Veg',
        description: 'Chicken Biryani = Rs 250,                           Mutton Biryani = Rs 300',
        price: "Rs 195",        
        image: require('../assets/images/biryani.jpg'),
      },
      {        
        id: '4',
        name: 'Lamb Curry',        
        description: 'This authentic Indian lamb curry is made with lamb shoulder. It is simmered with fragrant spices, caramelized onions, and Greek yogurt until fork-tender. Served over naan or rice, this is a meal on its own',
        price: "Rs 395",        
        image: require('../assets/images/lambCurry.jpg'),
      },
    ],
  },
  {
    id: '5',
    name: 'Soup',
    items: [
      {
        id: '0',
        name: 'Smoked Mushroom soup',
        description: '1 free Strongbow Gold Apple 250ml',
        price: "Rs 175",
        image: require('../assets/images/mushroomSoup.jpg'),
      },
      {
        id: '1',
        name: 'Sao Mai (BEEF)',
        description: 'A spicy lemongrass beef noodle soup with beef shank, served with a side of Bean Sprouts, Jalapenos, Basil, lime, topped with scallions, cilantro and some thinly sliced medium rare beef',
        price: "Rs 400",
        image: require('../assets/images/beefSoup.jpg'),
      },
      {
        id: '2',
        name: 'Sao Mai(SEAFOOD)',
        description: 'House special soup served with vermicelli noodles, chopped lettuce, shrimp, fish ball and fish cake in a chicken broth served with Tofu & stir-fried mixed vegetables',
        price: "Rs 435",
        image: require('../assets/images/soupSeafood.jpg'),
      },
      {
        id: '3',
        name: 'Soup of the day',
        description: 'Served with 1 free Strongbow Gold Apple  chilled drink 250ml',
        price: "Rs 260",
        image: require('../assets/images/food12.png'),
      },
    ],
  },
  {
    id: '6',
    name: 'Snacks',
    items: [
      {
        id: '0',
        name: 'Pav Bhaji 3PCS ',
        description: '1 free Strongbow Gold Apple 250ml',
        price: "Rs 155",
        image: require('../assets/images/pavBhaji.jpg'),
      },
      {
        id: '1',
        name: 'Samoussa Veg 6PCS',
        description: 'Samoussa Chicken 6PCS = RS 180, Samoussa Cheese 6PCS = Rs 150',
        price: "Rs 170",
        image: require('../assets/images/samoussa.jpg'),
      },
      {
        id: '2',
        name: 'SUSHI',
        description: 'Nigiri 4PCS = Rs 350,                               California 4PCS = Rs 300,       Maki 4PCS = Rs 200,       Sashimi 4PCS = Rs 375',
        price: "",
        image: require('../assets/images/sushi.jpg'),
      },
      {
        id: '3',
        name: 'Spring Rolls ',
        description: 'Veg = Rs 160,     Chicken = Rs 175,                   Tuna = Rs 180',
        price: "",
        image: require('../assets/images/SpringRolls.jpg'),
      },
      {
        id: '4',
        name: 'Garlic Bread with Cheese Bites ',
        description: 'served with apple juice',
        price: "Rs 200",
        image: require('../assets/images/garlicCheeseBread.jpg'),
      },
      {
        id: '5',
        name: 'French Fries ',
        description: 'Served with 1 free Pepsi 1L',
        price: "Rs 125",
        image: require('../assets/images/frenchFries.jpg'),
      },
    ],
  },
  {
    id: '7',
    name: 'Brunch Menu',
    items: [
      {
        id: '0',
        name: 'Carrot Cake ',
        description: 'Top this dense carrot cake, a classic pleaser with homemade cream cheese frosting',
        price: "Rs 195",
        image: require('../assets/images/carrotcake.jpg'),
      },
      {
        id: '1',
        name: 'Egg Crepes',
        description: 'Baked Egg Crepes with spring herbs and avocado with a sprinkle of dill, basil and chives',
        price: "Rs 180",
        image: require('../assets/images/eggCrepes.jpg'),
      },
      {
        id: '2',
        name: 'Sandwiches',
        description: 'Loaded with herb sausages patties, eggs, tomato, and parsley',
        price: "Rs 125",
        image: require('../assets/images/sandwiches.jpg'),
      },
      {
        id: '3',
        name: 'Four-Cheese Scalloped Potatoes',
        description: 'Sliced potatoes with heavy cream and mozzarella, asiago and raclette cheeses',
        price: "Rs 245",
        image: require('../assets/images/scalloped.jpg'),
      },
      {
        id: '4',
        name: 'Baked Ham with Brown Sugar Mustard Glaze ',
        description: 'Baked ham is moist, tender and delicious inside while the outside is brushed with a brown sugar glaze and caramelized for a hint of sweetness',
        price: "Rs 250",
        image: require('../assets/images/ham.jpg'),
      },
      {
        id: '5',
        name: 'Quiche',
        description: 'Heavy creams, eggs, green onions & biscuits',
        price: "Rs 225",
        image: require('../assets/images/quiche.jpg'),
      },
    ],
  },
  {
    id: '8',
    name: 'Drinks/Beverages',
    items: [
      {
        id: '0',
        name: 'Ice Tea ',
        description: '1L = Rs 120, 1.5L = Rs 140, 2L = Rs 155',
        price: "",
        image: require('../assets/images/icedTea.jpg'),
      },
      {
        id: '1',
        name: 'Orange Juice',
        description: '',
        price: "Rs 65",
        image: require('../assets/images/OJ.jpg'),
      },
      {
        id: '2',
        name: 'Strawberry Lemonade',
        description: '',
        price: "Rs 75",
        image: require('../assets/images/strawbeerylemonade.jpg'),
      },
      {
        id: '3',
        name: 'Pepsi',
        description: '1L = Rs 135, 1.5L = Rs 165, 2L = Rs 200',
        price: "",
        image: require('../assets/images/Pepsi1.jpg'),
      },
      {
        id: '4',
        name: 'Bloody Mary',
        description: 'Served cold',
        price: "Rs 120",
        image: require('../assets/images/bloodyMary.jpg'),
      },
      {
        id: '5',
        name: 'Mojito',
        description: 'Served cold',
        price: "Rs 175",
        image: require('../assets/images/mojito.jpg'),
      },
      {
        id: '6',
        name: 'Crystal Water Bottle',
        description: '1L = Rs 115, 1.5L = Rs 135, 2L = Rs 170',
        price: "",
        image: require('../assets/images/water.png'),
      },
    ],
  },
  {
    id: '9',
    name: 'Reviews',
    items: [
      {
        id: '0',
        name: 'Anne Marie Begue ',
        description: 'This cozy restaurant has left the best impressions! Hospitable hosts, delicious dishes, beautiful presentation, wide wine list and wonderful dessert. I recommend to everyone! I would like to come back here again and again. Definitely worth 5 stars!',
        price: "",
        image: require('../assets/images/apple.png'),
      },
      {
        id: '1',
        name: 'Natasha Sewpal',
        description: 'First time in Belle Vue Maurel and YOU have to go! It’s the cutest little spot with amazing food. The Italian dishes are to die for. IT WAS FIRE!! The service we received was so amazing and we will definitely be back again. They made us feel welcomed and gave us an amazing experience.',
        price: "",
        image: require('../assets/images/banana.png'),
      },
      {
        id: '2',
        name: 'Michael Jean Pierre',
        description: 'It’s a great experience. The ambiance is very welcoming and charming. Amazing wines, food and service. Staff are extremely knowledgeable and make great recommendations.',
        price: "",
        image: require('../assets/images/grape.png'),
      },
      {
        id: '3',
        name: 'Yashwini Seechurn',
        description: 'This place is great! Atmosphere is chill and cool but the staff is also really friendly. They know what they’re doing and what they’re talking about, and you can tell making the customers happy is their main priority. Food is pretty good, some italian classics and some twists, and for their prices it’s 100% worth it.',
        price: "",
        image: require('../assets/images/peach.png'),
      },
      {
        id: '4',
        name: 'Laura Ramdoo',
        description: 'Do yourself a favor and visit this lovely restaurant in Belle Vue Maurel. The service is unmatched. The staff truly cares about your experience. The food is absolutely amazing – everything we tasted melted in other mouths. Absolutely the best meal we had in the resto lounge. Highly recommend!',
        price: "",
        image: require('../assets/images/mango.png'),
      },
      {
        id: '5',
        name: 'Preyaa Rambrichh',
        description: 'When we think about celebrations, Au Bureau Lounge is always our first option and it never disappoints. From the starter to the dessert the quality and tastes of everything was outstanding, my purple velvet cake might have been the best meal I have ever been served. Service was delightful and very professional. 10/10',
        price: "",
        image: require('../assets/images/plum.png'),
      },
      {
        id: '6',
        name: 'Daniel Seebaluck',
        description: ' I have to say, I enjoyed every single bite of the meal in this resto-bar lounge. I had a 3 course meal, with a couple of beers. Considering the quality, the price is reasonable. Ideal for those who want a romantic night out. There was also plenty of room for bigger groups.',
        price: "",
        image: require('../assets/images/blueberry.png'),
      },
      {
        id: '7',
        name: 'Alvin Ramanah',
        description: 'Excellent food. Menu is extensive and seasonal to a particularly high standard. Definitely fine dining. We are so fortunate to have this place just a few minutes drive away from home. Food is stunning, both the tapas and downstairs restaurant. Cocktails wow, wine great and lovely selection of beers. Love this place and will continue to visit.',
        price: "",
        image: require('../assets/images/cherry.png'),
      },
      {
        id: '8',
        name: 'Raj Locknauth',
        description: 'Amazing experience! If you thought gourmet kitchen will leave you hungry, think again. You should skip several meals before visiting this amazing restaurant. Everything is so tasty, you cannot restraint yourself from having all of the dishes.',
        price: "",
        image: require('../assets/images/apple.png'),
      },
    ],
  },

];

